### PR TITLE
Remove html links

### PR DESCRIPTION
**Pull request by Silex**
Just a test to see if it fixes the rendering.

### CODE REVIEW

**Comment by Fuco1** [comment]
It seems github now adds those anchors automatically, because I can navigate just fine.  I guess we could merge this.

**Comment by Fuco1** [comment]
Well, I take that back, some links do not work.

**Comment by Silex** [comment]
Yeah, we need to test each link and correct them :-/

**Comment by Fuco1** [comment]
Yes, only for TOC.

**Comment by Silex** [comment]
Alright, added an updated TOC

https://github.com/Fuco1/dired-hacks/tree/update-readme

**Pull request merged**
