### PR TITLE
Sort lines in dired-filter-group-mode

### PR DESCRIPTION
**Pull request by stakemori**
Thank you for writing useful code.
But in `dired-filter-group-mode`, sometimes lines are not sorted and there is a header with no lines. Please see [this screnshot](http://i.imgur.com/L1lJPp7.png). Here I set `dired-filter-group-saved-groups` to `(("default" ("Symlink" (symlink)) ("Python" (extension . "py"))))`.

Merging this pull request will fix this.

### CODE REVIEW

**Comment by Fuco1** [comment]
What happens if you revert the buffer? (hit `g`)  It should remove the empty drawers.  I'm also thinking it might have to do with the apanese, maybe some broken regexp somewhere.

**Comment by Fuco1** [comment]
I'm looking at the code but I don't understand where is the sorting done.  It seems you are only inserting things in reverse order?

**Comment by stakemori** [comment]
Thanks for the reply.

> What happens if you revert the buffer?

Nothing happens.

>  It seems you are only inserting things in reverse order?

No. Because the last pushed line will be inserted first, it is not the reverse order. This `dired-filter-group--apply` is almost same as yours. There is a little difference. The point in the example above is that `b.py` is a symbolic link and a Python file.

First, in the `--each` loop in your `dired-filter-group--apply`, these lines
<pre>
a.py
b.py
</pre>
become as follows because `b.py` is a symlink.
<pre>
[ Symlink ]
b.py
a.py
</pre>
Then because they are Python files, they become  as follows.
<pre>
[ Symlink ]
[ Python ]
b.py
a.py
</pre>
So these lines are not sorted.

**Comment by Fuco1** [comment]
Ooooh, I see!  Very clever!  I guess I never used overlapping filters so I've never noticed.

Thanks for the explanation.  I'll finish some things I'm in the middle of and take care of this!

**Comment by Fuco1** [comment]
Okey, merged, thanks again!

I think I will add another feature on top of this, where you can add adjust priorities of when the group is "resolved" (right now, both drawing order and filter priority is determined by the order in the list, but sometimes I want to draw e.g. symlinks as first group but have it override all other filters -> which now I could only get by placing it as the last group).

**Comment by stakemori** [comment]
Thank you. I am looking forward to the new feature.

**Pull request merged**
