### PR TITLE
dired-rainbow-file-regexp-group

### PR DESCRIPTION
**Pull request by mnewt**
Adds configurability of the file name font locking region. Partially (and probably satisfactorily) addresses #151.

### CODE REVIEW

**Comment by mnewt** [comment]
@Fuco1 What do you think? It addresses my use case and doesn't modify things too much. Kind of weird to expose the regexp group as a `defcustom` but I hope the docstring makes it clear enough.

**Comment by mnewt** [comment]
Or maybe there is another way to accomplish this? It seems like the `font-lock-add-keywords` arg `how` might handle this case but if so I haven't been able to figure out how

**Comment by Fuco1** [comment]
Yes, font-lock is pretty mysterious.  Most of what I've learned about it was acomplished by reading the sources.

I think the `how` argument might be useful here but it only handles how you update the styles, which means this package would somehow need to ensure it runs after diredfl or anything else.  Which might get tricky.

**Comment by mnewt** [comment]
I learned more about font locking and was able to accomplish this by doing two things. Maybe this will help someone else.

First, move the file extension keyword to the end using `how`. Second, set `override` to `t`. The idea is to let `dired-rainbow` go ahead and highlight the whole file name. Then afterwards override the extension part. At least I think that's what it's doing! It looks like this:

    (font-lock-add-keywords 'dired-mode '(("\\.[^./]*?$" 0 shadow t)) 'end)

@Fuco1 Thanks for pointing me in the right direction!

**Pull request closed without merging**
